export enum InconsistencyIssueEnum {
    'LNG_PAGE_INCONSISTENCY_LABEL_BIGGER' = '>',
    'LNG_PAGE_INCONSISTENCY_LABEL_BIGGER_OR_EQUAL' = '>=',
    'LNG_PAGE_INCONSISTENCY_LABEL_SMALLER' = '<',
    'LNG_PAGE_INCONSISTENCY_LABEL_SMALLER_OR_EQUAL' = '<=',
    'LNG_PAGE_INCONSISTENCY_LABEL_NOT_EQUAL' = '!=',
    'LNG_PAGE_INCONSISTENCY_LABEL_EQUAL' = '='
}
