export enum ModulePath {
    AuthenticationModule = 'auth',
    AccountModule = 'account',
    UserModule = 'users',
    UserRoleModule = 'user-roles',
    OutbreakModule = 'outbreaks',
    OutbreakTemplatesModule = 'outbreak-templates',
    ContactModule = 'contacts',
    CaseModule = 'cases',
    EventModule = 'events',
    DuplicateRecordsModule = 'duplicated-records',
    ClusterModule = 'clusters',
    RelationshipModule = 'relationships',
    ReferenceDataModule = 'reference-data',
    LocationModule = 'locations',
    DashboardModule = 'dashboard',
    TransmissionChainModule = 'transmission-chains',
    ImportExportDataModule = 'import-export-data',
    SystemConfigModule = 'system-config',
    TeamModule = 'teams',
    AuditLogModule = 'audit-log',
    CloudBackupModule = 'cloud-backup',
    TermsOfUseModule = 'terms-of-use',
    LanguageModule = 'languages',
    HelpModule = 'help'
}
